### ISSUE TITLE
Would `https://genius.com/robots.txt` be an option?

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#63]
Actually when I first touched these codes, I don't understand why it is `https://www.youtube.com/robots.txt`.

For interactions between top frame and iframe, we can just use `postMessage` to do.

If we go for `https://genius.com/robots.txt`, we can use the native fetch API to do which is exactly the same implementation in single-page application (SPA).

#### How?

1. Top Window
2. Create Iframe pointing to `https://genius.com/robots.txt`
3. When `https://genius.com/robots.txt` is loaded, `postMessage` to top frame to ask for what you want
4. top frame response the iframe what he wants
5. `https://genius.com/robots.txt` do his job (same-origin, like SPA). _I have done before that location href can be also faked with history API `replaceState`, and the REFERER sent in native fetch can be changed too_
6. once iframe found its result, send it back to the top frame.
7. when the iframe first ask the top frame, the asking will be associated with a timestamp, and that timestamp will be treated as unique id for communication. request and response shall match their unique id.

### Remarks

Recently, i switched to Brave+ViolentMonkey, and i cannot fetch the lyrics too. (but the reason is different, the solution might require to change the communication between iframe and top frame).

If you just create a Iframe with the same origin as the top window, what is the point of creating iframe? You can just use GM.xmlHttpRequest in your top frame.

### Related

I noted that

     My other Userscripts that use this library:
  
     https://github.com/cvzi/Bandcamp-script-deluxe-edition

is mentioned in the README. I did not read its code but I guess such a big change might break something there?

**Comment by cyfung1031** [comment]
The coding will be using async/await as well.

Iframe Userscript:
```js
//inside iframe

mutex = new Mutex()
function startCommunication(request) {

  mutex.lockWith(async (unlock)=>{ // wait until last request is finished.

    // {{ if there is no cache }}

    let fetchURLResponse = await fetch(...) // as per request

    // ...
    // await { add annonation }
    // ..
    // await { do caching } - (on origin: genius.com) - youtube / spotify / ... same cache
    // ...

    let finished = await new Promise(resolve => {


      window.addEventListener('message', ()=>{
        // remove this event handler

        // top frame confirmed received
        //...
        resolve(...) 


      });

      top.postMessage(...) // send back the final result


    })

    unlock(); 
  })


}

window.addEventListener('message', ()=>{
  // recevie top frame request  
  startCommunication(request) // eg search title, get lyrics, etc
})

// ... send to top frame iframe is loaded
top.postMessage(...)

```

TopFrame Userscript:
```js
// top frame

let iframeDeferred = new Deferred()
window.addEventListener('message', () => {

  // iframe ready 
  iframeDeferred.resolve();


})

// create Iframe

function makeRequest(request){

  iframeDeferred.debounce(()=>{

    // execute after iframe is ready

    iframeWindow.postMessage(...) // send request

  })

}



``

**Comment by cyfung1031** [comment]
Issue Closed.
Not Working - as iframe cannot be displayed.

**Comment by cvzi** [comment]
(You can ignore https://github.com/cvzi/Bandcamp-script-deluxe-edition if you want to make changes)

Originally I just used the whole HTML content from genius.com and displayed it in the iframe. That was simple and the iframe guaranteed that it looked the same on Spotify, Youtube, etc because it is not affected by the CSS of the parent page. Same origin was added later because of CSP (?) restrictions.

We now modify the genius.com HTML content heavily, before displaying it. Maybe now it can be done without an iframe. Extract lyrics from genius.com HTML and then display the lyrics in the top level page with custom stylesheet instead of genius.com-stylesheet. 

I saw there is a CSS property to reset an element to "no css style", maybe that can be used instead of an iframe to reset CSS: https://stackoverflow.com/questions/15901030/how-to-reset-remove-css-styles-for-a-specific-element-or-selector-only/15903168#15903168 (I have never used this though, I don't know if it works well).

**Comment by cyfung1031** [comment]
I see. Using Iframe to render the content makes sense. Open Shadow DOM is also an option.

So the communication between top and iframe can be much easier, as the network request is by the UserScript manager without cors issue.

Iframe could just act as a renderer. It receives the page content from top window.
