### ISSUE TITLE
[Bug] Deleted Lyrics is shown

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#77]
#### Reproduction:
Goto https://www.youtube.com/watch?v=JMzDWbqROT4
Search (Auto/Manual) "Girls Dead Monster All Song"

#### Search Result:
<img width="400" alt="Screen Shot 2024-06-21 at 17 06 25" src="https://github.com/cvzi/genius-lyrics-userscript/assets/44498510/bf0d621d-14b5-42ff-8a75-2ed3cdf47544">

#### Lyrics Content: 
* [genius lyrics page](https://genius.com/Deleted-artist-replaced-song-lyrics)
<img width="402" alt="Screen Shot 2024-06-21 at 17 07 15" src="https://github.com/cvzi/genius-lyrics-userscript/assets/44498510/8ddd869c-2ffa-40ff-b166-8d72b9b1ef20">

@cvzi

**Comment by cvzi** [comment]
When you opened the issue, I was able to reproduce this, but now I can't reproduce it. I get zero search results now, also when I search on the genius.com website.

Maybe this happens when genius.com deletes a song, but the genius-search doesn't immediately update its search-index. So the search returns outdated results for some time.

**Comment by cyfung1031** [comment]
As we cannot reproduce this issue now, let's do in a simpler way.

Based on what we know, the author will become "Deleted Artist" if the lyrics has been deleted.
So, the filter will be added to filter out these "Deleted Artist"'s lyrics.
